NativeJS=new(Object)();NativeJS.Array=Array;NativeJS.Boolean=Boolean;NativeJS.Date=Date;NativeJS.Function=Function;NativeJS.Math=Math;NativeJS.Number=Number;NativeJS.String=String;$u=undefined;var Red=function Object(){this.m$initialize.apply(this,arguments)};;Function.prototype.m$_as=function _as(o){var _f=this;var p=function(){return _f.apply(o,arguments);};return p;};Function.prototype.m$instanceEval=function instanceEval(block){return block.m$_as(this)()};Red.m$instanceEval=function instanceEval(block){return block.m$_as(this)()};Object.prototype.m$inspect=function(){return this.toString();};var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Red[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Red.prototype[_x]=Red.prototype[_x];};};
Red.m$superclass=function superclass(){return Red;};
Red.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Red;};
var object=$u,property=$u,bubble=$u,result=$u;Red.c$I=100;
Red.m$superclass=function(){return nil;};
_o.m$objectId=function(){return this.i$objectId;};
_o.m$objectIdEql=function(x){return this.i$objectId=x;};
_o.m$initialize=function(){this.m$_assignId();};
_o.m$_brkt=function(x){return this[x];};
_o.m$_breq=function(x,y){return this[x] = y;};
_o.m$clone=function(){var object=$u,property=$u;object=new(Red)();for(var property in this){if($T(property == 'i$objectId')){continue;};object[property] = this[property];};return(object);};
_o.m$dup=function(){var object=$u,property=$u;object=new(this.m$class())();for(var property in this){if($T(property == 'i$objectId')){continue;};if($T(property.slice(0,1) == ('$'))){object[property] = this[property];};};return(object);};
_o.m$_eql2=function(otherObject){return this.i$objectId == otherObject.m$objectId();};
_o.m$eqlBool=function(otherObject){return this.i$objectId == otherObject.m$objectId();};
_o.m$equalBool=function(otherObject){return this.i$objectId == otherObject.m$objectId();};
_o.m$_eql3=function(otherObject){return this.m$_eql2(otherObject);};
_o.m$extend=function(){return nil;};
_o.m$inspect=function(){return this.m$toS();};
_o.m$instanceEval=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');return block.m$_as(this)();};
_o.m$instanceOfBool=function(klass){return klass.m$_eql2(this.m$class());};
_o.m$isABool=function(klass){var bubble=$u,result=$u;bubble=this.m$class();while(!$T(bubble.m$_eql2(Red))){if($T($T(_a=klass.m$_eql2(Red))?_a:klass.m$_eql2(bubble))){result=true;};if($T(result)){break;};bubble=bubble.m$superclass();};return $T(_a=result)?_a:klass.m$_eql2(Red);};
_o.m$methods=function(){var result=$u,property=$u;result=[];for(var property in this){if($T(property.slice(0,2)=='m$')){result.m$push($q(property.slice(2,property.length)));};};return result;};
_o.m$nilBool=function(){return false;};
_o.m$respondToBool=function(methodName){return typeof this[methodName] == 'function';};
_o.m$send=function(methodName,args){return this[methodName].apply(this,args);};
_o.m$toS=function(){return $Q('#<',this.m$class().m$toS(),':',this.m$objectId(),'>');};
_o.m$_assignId=function(){this.m$objectIdEql(Red.c$I++);return(this);};
_o.toString=function(){return this.m$inspect().toString()};});var Module=function Module(){this.m$initialize.apply(this,arguments)};;var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Module[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Module.prototype[_x]=Red.prototype[_x];};};
;
Module.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Module;};
var writer=$u;_o.m$initialize=function(){this.i$_methods=new(Red)();};
_o.m$attr=function(a,writer){writer=$T(_a=writer)?_a:false;this.prototype['m$'+a]=function(){return this['i$'+a];};;if($T(writer)){this.prototype['m$'+a+'Eql']=function(x){return this['i$'+a]=x;};;};return(nil);};
_o.m$cattr=function(a,writer){writer=$T(_a=writer)?_a:false;this.prototype['m$'+a]=function(){return this['c$'+a];};;if($T(writer)){this.prototype['m$'+a+'Eql']=function(x){return this['c$'+a]=x;};;};return(nil);};
_o.m$jattr=function(a,writer){writer=$T(_a=writer)?_a:false;this.prototype['m$'+a]=function(){return this[a];};;if($T(writer)){this.prototype['m$'+a+'Eql']=function(x){return this[a]=x;};;};return(nil);};});var Class=function Class(){this.m$initialize.apply(this,arguments)};;var _x;for(_x in Module){if(_x.slice(0,2)==='c$'){Class[_x]=Module[_x];};};
var _x;for(_x in Module.prototype){if(_x.slice(0,2)==='m$'){Class.prototype[_x]=Module.prototype[_x];};};
;
Class.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Class;};
_o.m$superclass=function(){return this.i$superclass;};
_o.m$superclassEql=function(superclass){return this.i$superclass=superclass;};
_o.m$_eql2=function(object){return this.m$toS().toString() == object.m$toS().toString();};
_o.m$toS=function(){return Proc.m$toS.call(this);};});for(var x in Class.prototype){Red[x]=Class.prototype[x];};for(var x in Class.prototype){Function[x]=Class.prototype[x];};for(var x in Class.prototype){Module[x]=Class.prototype[x];};for(var x in Class.prototype){Array[x]=Class.prototype[x];};for(var x in Class.prototype){Number[x]=Class.prototype[x];};for(var x in Class.prototype){String[x]=Class.prototype[x];};for(var x in Class.prototype){Class[x]=Class.prototype[x];};NilClass=function NilClass(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){NilClass[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){NilClass[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){NilClass.prototype[_x]=Red.prototype[_x];};};
NilClass.m$superclass=function superclass(){return Red;};
NilClass.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return NilClass;};
_o.m$class=function(){return NilClass;};
_o.m$initialize=function(){this.m$objectIdEql(4);if($T(!(typeof(nil) == 'undefined'))){return(false);};};
_o.m$_ampe=function(object){return false;};
_o.m$_pipe=function(object){return ($T(object)?true:false);};
_o.m$_care=function(object){return ($T(object)?true:false);};
_o.m$inspect=function(){return $q('nil');};
_o.m$nilBool=function(){return true;};
_o.m$toA=function(){return [];};
_o.m$toF=function(){return 0;};
_o.m$toI=function(){return 0;};
_o.m$toS=function(){return $q('');};
_o.toString=function(){return 'nil'};
nil=new NilClass;
delete NilClass.prototype.m$initialize;});Proc=Function;var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Proc[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Proc.prototype[_x]=Red.prototype[_x];};};
Proc.m$superclass=function superclass(){return Red;};
Proc.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Proc;};
_o.m$classEval=function(){return nil;};
_o.m$toS=function(){return $q(this.toString().match(/^function (\w*)\(/)[1]);};
_o.m$inspect=function(){return $q('function()');};
_o.m$=function(o){var _f=$u,p=$u;_f=this;p=function(){return _f.apply(o,arguments);};p.i$_arity=this.arity;return p.m$_assignId();};});Proc=function Proc(){};var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Array[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Array.prototype[_x]=Red.prototype[_x];};};
Array.m$superclass=function superclass(){return Red;};
Array.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Array;};
var result=$u,i=$u,object=$u,length=$u,index=$u,final=$u,a=$u,b=$u,c=$u,originalSize=$u,temp=$u,block=$u,array=$u,separator=$u,string=$u,quantity=$u,last=$u,j=$u,flip=$u,max=$u,store=$u;_o.m$_ampe=function(otherArray){var result=$u,i=$u;result=[];for(var i=0,l=this.length;i<l;++i){if($T(otherArray.m$includeBool(this[i]))){result.m$push(this[i]);};};return(result);};
_o.m$_pipe=function(otherArray){return this.m$concat(otherArray).m$uniqBang();};
_o.m$_star=function(object){var result=$u,i=$u;if($T(object.constructor==String)){return(this.m$join(object));};result=[];i=0;while($T(i<object)){result=result.concat(this);i=i.m$_plus(1);};return(result);};
_o.m$_plus=function(otherArray){return this.concat(otherArray);};
_o.m$_subt=function(otherArray){var result=$u,i=$u;result=[];for(var i=0,l=this.length;i<l;++i){if(!$T(otherArray.m$includeBool(this[i]))){result.m$push(this[i]);};};return(result);};
_o.m$_ltlt=function(object){this[this.length] = object;return(this);};
_o.m$_ltgt=function(otherArray){return nil;};
_o.m$_eql2=function(object){var i=$u;if(!$T(object.constructor == Array)){return(false);};for(var i=0,l=this.length;i<l;++i){if($T(this[i].m$_eql2)){if(!$T(this[i].m$_eql2(object[i]))){return(false);};}else{if(!$T(this[i] === object[i])){return(false);};};};return(true);};
_o.m$_brkt=function(index,length){return this.m$slice(index,length);};
_o.m$_breq=function(index){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);args=[];var i;for(i=1;i<_l;++i){args.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);var object=$u,length=$u,final=$u,a=$u,b=$u,c=$u;object=args.m$pop();if(!$T(args.m$emptyBool())){length=args.m$first();};if($T(index<0)){index=index.m$_plus(this.length);};if($T(index<0)){return(nil);};while($T(this.length<index)){this.m$push(nil);};if($T(length)){final=($T(index+length>this.length)?this.length:index+length);a=this.m$slice(0,index);b=this.m$slice(final,this.length-1);c=($T(object.m$_eql2(nil))?a.concat(b):($T(object.m$isABool(Array))?a.concat(object).concat(b):a.m$push(object).concat(b)));this.m$replace(c);}else{this[index]=object;};return(object);};
_o.m$abbrev=function(words){return nil;};
_o.m$assoc=function(object){var i=$u;for(var i=0,_l=this.length;i<_l;++i){if($T((_a=$T(this[i].m$isABool(Array)))?((_c=$T(_b=this[i][0].m$_eql2(object)))?_b:_c):_a)){return(this[i]);};};return(nil);};
_o.m$at=function(index){if($T(index<0)){index=index.m$_plus(this.length);};if($T(index<0||index>=this.length)){return(nil);};return this[index];};
_o.m$clear=function(){this.length = 0;return(this);};
_o.m$collect=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');return this.m$map(block);};
_o.m$collectBang=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');return this.m$mapBang(block);};
_o.m$compact=function(){return $T(_a=this.m$dup().m$compactBang())?_a:this;};
_o.m$compactBang=function(){var originalSize=$u;originalSize=this.m$size();this.m$delete(nil);return(($T(originalSize.m$_eql2(this.m$size()))?nil:this));};
_o.m$concat=function(otherArray){return this.m$replace(this.concat(otherArray));};
_o.m$delete=function(value,_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var originalSize=$u,temp=$u,i=$u;originalSize=this.m$size();temp=[];for(var i=0,l=this.length;i<l;++i){if(!$T(value.m$_eql2(this[i]))){temp.m$push(this[i]);};};this.m$replace(temp);return ($T(originalSize.m$_eql2(this.m$size()))?($T(blockGivenBool)?_block():nil):value);};
_o.m$deleteAt=function(index){var result=$u,temp=$u,i=$u;if($T(index.m$_lthn(0))){index=index.m$_plus(this.m$size());};if(!$T((_a=$T(index.m$_lthn(this.m$size())))?((_c=$T(_b=index.m$_gteq(0)))?_b:_c):_a)){return(nil);};result=this[index];temp=[];for(var i=0,l=this.length;i<l;++i){if(!$T(i.m$_eql2(index))){temp.m$push(this[i]);};};this.m$replace(temp);return(result);};
_o.m$deleteIf=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var temp=$u,i=$u;temp=[];for(var i=0,l=this.length;i<l;++i){if(!$T(_block(this[i]))){temp.m$push(this[i]);};};return this.m$replace(temp);};
_o.m$dup=function(){return this.m$class().m$superclass().prototype.m$dup.apply(this,arguments).m$concat(this);};
_o.m$each=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var i=$u;for(var i=0,l=this.length;i<l;++i){_block(this[i]);};return(this);};
_o.m$eachIndex=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var i=$u;for(var i=0,l=this.length;i<l;++i){_block(i);};return(this);};
_o.m$emptyBool=function(){return this.length==0;};
_o.m$eqlBool=function(otherArray){return this.m$equalBool(otherArray)||this.m$_eql2(otherArray);};
_o.m$fetch=function(index,block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');if($T(index<0)){index=index.m$_plus(this.length);};if($T(index<0||index>=this.length)){return(($T(typeof(block)=='function')?block(index):$T(_a=block)?_a:nil));}else{return(this.m$at(index));};};
_o.m$fill=function(object,index,length,_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');index=$T(_a=index)?_a:0;length=$T(_a=length)?_a:nil;var final=$u,i=$u,block=$u;if(!$T(typeof(object)=='function'||typeof(index)=='function'||typeof(length)=='function')){if($T(index<0)){index=index.m$_plus(this.length);};final=($T(length)?index+length:this.length);for(var i=index;i<final;++i){this[i]=object;};return(this);};final=this.length;if($T(typeof(object)=='function')){block=object;};if($T(typeof(index)=='function')){block=index;index=object;};if($T(typeof(length)=='function')){block=length;length=index;index=object;if($T(index<0)){index=index.m$_plus(this.length);};final=index+length;};if($T(index<0)){index=index.m$_plus(this.length);};for(var i=index;i<final;++i){this[i] = _block(i);};return(this);};
_o.m$first=function(quantity){return this.m$slice(0,quantity);};
_o.m$flatten=function(){var result=$u,i=$u;result=[];for(var i=0,l=this.length;i<l;++i){if($T(this[i].constructor==Array)){result.m$concat(this[i].m$flatten());}else{result.m$push(this[i]);};};return(result);};
_o.m$flattenBang=function(){var originalSize=$u;originalSize=this.m$size();this.m$replace(this.m$flatten());return(($T(originalSize.m$_eql2(this.m$size()))?nil:this));};
_o.m$includeBool=function(object){var i=$u;for(var i=0,l=this.length;i<l;++i){if($T(this[i].m$_eql2(object))){return(true);};};return(false);};
_o.m$index=function(object){var i=$u;for(var i=0,l=this.length;i<l;++i){if($T(this[i].m$_eql2(object))){return(i);};};return(nil);};
_o.m$insert=function(index){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);args=[];var i;for(i=1;i<_l;++i){args.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);var result=$u,i=$u;result=[].m$concat(this.m$slice(0,index));for(var i=0,l=args.length;i<l;++i){result.m$push(args[i]);};result.m$concat(this.m$slice(index,this.length - 1));return this.m$replace(result);};
_o.m$inspect=function(){var array=$u,i=$u;array=[];for(var i=0,l=this.length;i<l;++i){array.m$push(this[i].m$inspect());};return $q('[').m$_plus(array.m$join($q(', '))).m$_plus($q(']'));};
_o.m$join=function(separator){separator=$T(_a=separator)?_a:$q('');var string=$u,i=$u;string=$q('');for(var i=0,l=this.length;i<l;++i){if(!$T(string.m$_eql2($q('')))){string=string.m$_plus(separator);};string=string.m$_plus(($T(this[i].m$isABool(Array))?this[i].m$join(separator):this[i].m$toS()));};return(string);};
_o.m$last=function(quantity){quantity=$T(_a=quantity)?_a:nil;if(!$T(quantity)){return(this.m$slice(-1));};if($T(quantity.m$_lteq(0))){return([]);};return this.m$slice(($T(this.m$size().m$_gthn(quantity))?(0).m$_subt(quantity):0),quantity);};
_o.m$length=function(){return this.length;};
_o.m$map=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');return this.m$dup().m$mapBang(block);};
_o.m$mapBang=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var i=$u;for(var i=0,l=this.length;i<l;++i){this[i]=_block(this[i]);};return(this);};
_o.m$nitems=function(){return this.m$compact().m$size();};
_o.m$pop=function(){if($T(this.length==0)){return(nil);};return this.pop();};
_o.m$push=function(object){this[this.length]=object;return(this);};
_o.m$rassoc=function(object){var i=$u;for(var i=0,l=this.length;i<l;++i){if($T((_a=$T(this[i].m$isABool(Array)))?((_c=$T(_b=this[i][1].m$_eql2(object)))?_b:_c):_a)){return(this[i]);};};return(nil);};
_o.m$reject=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var result=$u,i=$u;result=[];for(var i=0,l=this.length;i<l;++i){if(!$T(_block(this[i]))){result.m$push(this[i]);};};return(result);};
_o.m$rejectBang=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var originalSize=$u;originalSize=this.m$size();this.m$deleteIf(block);return ($T(originalSize.m$_eql2(this.m$size()))?nil:this);};
_o.m$replace=function(otherArray){var i=$u;this.m$clear();for(var i=0,l=otherArray.length;i<l;++i){this.m$push(otherArray[i]);};return(this);};
_o.m$reverse=function(){return this.m$dup().m$reverseBang();};
_o.m$reverseBang=function(){var last=$u,i=$u,j=$u;last=this.length-1;for(var i=0,l=this.length;i<l;++i){j=last-i;if(!$T(i<j)){break;};this.m$_swap(i,j);};return(this);};
_o.m$reverseEach=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');this.m$reverse().m$each(block);return(this);};
_o.m$rindex=function(value){var last=$u,flip=$u,i=$u;last=this.length-1;flip=this.m$reverse();for(var i=0,l=flip.length;i<l;++i){if($T(flip[i].m$_eql2(value))){return(last-i);};};return(nil);};
_o.m$select=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var result=$u,i=$u;result=[];for(var i=0,l=this.length;i<l;++i){if($T(_block(this[i]))){result.m$push(this[i]);};};return(result);};
_o.m$shift=function(){if($T(this.length==0)){return(nil);};return this.shift();};
_o.m$size=function(){return this.length;};
_o.m$slice=function(index,length){var result=$u,max=$u,i=$u;if($T(index<0)){index=index.m$_plus(this.length);};if($T(length)){if($T($T(_a=index.m$_gthn(this.m$size()))?_a:index.m$_lthn(0))){return(nil);};result=[];max=($T(this.m$size().m$_lthn(index.m$_plus(length)))?this.m$size():index.m$_plus(length));for(var i=index;i<max;i++){result.m$push(this[i]);};return(result);}else{return(($T($T(_a=index.m$_gteq(this.m$size()))?_a:index.m$_lthn(0))?nil:this[index]));};};
_o.m$sliceBang=function(index,length){return nil;};
_o.m$sort=function(){return this.m$dup().m$sortBang();};
_o.m$sortBang=function(){return this.m$_quickSort(0,this.m$size());};
_o.m$toA=function(){if($T(this.m$instanceOfBool(Array))){return(this);};return Array.m$apply(nil,this);};
_o.m$toAry=function(){return this;};
_o.m$toS=function(){return this.m$join();};
_o.m$transpose=function(){return nil;};
_o.m$uniq=function(){return this.m$dup().m$uniqBang();};
_o.m$uniqBang=function(){var originalSize=$u,temp=$u,i=$u;originalSize=this.m$size();temp=[];for(var i=0,l=this.length;i<l;++i){if(!$T(temp.m$includeBool(this[i]))){temp.m$push(this[i]);};};this.m$replace(temp);return ($T(originalSize.m$_eql2(this.m$size()))?nil:this);};
_o.m$unshift=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);args=[];var i;for(i=0;i<_l;++i){args.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);return this.m$replace(args.concat(this));};
_o.m$valuesAt=function(args){return nil;};
_o.m$zip=function(){return nil;};
_o.m$_partition=function(first,last,pivot){var store=$u;var value=this[pivot];this.m$_swap(pivot,last);var store=first;for(var i=0,l=this.length;i<l;++i){if(i<first||i>=last){continue;};if(this[i]<=value){this.m$_swap(store,i);store++;};};this.m$_swap(last,store);return(store);};
_o.m$_quickSort=function(start,finish){if(finish-1>start){var pivot=start+Math.floor(Math.random()*(finish-start));var pivot=this.m$_partition(start,(finish-1),pivot);this.m$_quickSort(start,pivot);this.m$_quickSort((pivot+1),finish);};return(this);};
_o.m$_swap=function(x,y){swap=this[x];this[x]=this[y];this[y]=swap;return(this);};});Hash=function Hash(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){Hash[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Hash[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Hash.prototype[_x]=Red.prototype[_x];};};
Hash.m$superclass=function superclass(){return Red;};
Hash.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Hash;};
var result=$u,i=$u,x=$u,value=$u,contents=$u,object=$u,keys=$u,originalSize=$u,array=$u,size=$u,values=$u;Hash.m$_brkt=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);args=[];var i;for(i=0;i<_l;++i){args.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);var result=$u,i=$u;if($T(args.length==1&&args[0].constructor==Hash)){return(args.m$first());};result=new(Hash)();for(var i=0,l=args.length;i<l;i+=2){result.m$_breq(args[i],args[i+1]);};return(result);};
_o.m$initialize=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');this.i$_default=$T(_a=block)?_a:nil;this.i$_contents=new(Object)();};
_o.m$_eql2=function(otherHash){var x=$u;if(!$T(this.m$size().m$_eql2(otherHash.m$size()))){return(false);};for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};if(!$T((_a=$T(!(typeof(otherHash.i$_contents[x]) == 'undefined')))?((_c=$T(_b=this.i$_contents[x].m$_eql2(otherHash.i$_contents[x])))?_b:_c):_a)){return(false);};};return(true);};
_o.m$_brkt=function(k){if($T(this.m$hasKeyBool(k))){return(this.i$_contents[k.m$hash()]);}else{return(typeof(this.i$_default)=='function'?this.i$_default(this,k):this.i$_default);};};
_o.m$_breq=function(k,v){this.i$_contents[k.m$hash()]=v;return(v);};
_o.m$clear=function(){var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};delete(this.i$_contents[x]);};return(this);};
_o.m$default=function(){return nil;};
_o.m$defaultEql=function(){return nil;};
_o.m$defaultProc=function(){return nil;};
_o.m$delete=function(key){var value=$u;value=this.i$_contents[key.m$hash()];delete(this.i$_contents[key.m$hash()]);return(value);};
_o.m$deleteIf=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};if($T(_block(Hash.m$_x(x),this.i$_contents[x]))){delete(this.i$_contents[x]);};};return(this);};
_o.m$dup=function(){var result=$u,x=$u;result=new(Hash)();for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};result.i$_contents[x] = this.i$_contents[x];};return(result);};
_o.m$each=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};if($T(_block.i$_arity==1)){_block([Hash.m$_x(x),this.i$_contents[x]]);}else{_block(Hash.m$_x(x),this.i$_contents[x]);};};return(this);};
_o.m$eachKey=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};_block(Hash.m$_x(x));};return(this);};
_o.m$eachPair=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};_block(Hash.m$_x(x),this.i$_contents[x]);};return(this);};
_o.m$eachValue=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};_block(this.i$_contents[x]);};return(this);};
_o.m$emptyBool=function(){var x=$u;for(var x in this.i$_contents){if($T(x.slice(1,2)=='_')){return(false);};};};
_o.m$fetch=function(){return nil;};
_o.m$hasKeyBool=function(key){return !(typeof(this.i$_contents[key.m$hash()]) == 'undefined');};
_o.m$hasValueBool=function(value){var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};if($T(this.i$_contents[x].m$_eql2(value))){return(true);};};return(false);};
_o.m$includeBool=function(key){return this.m$hasKeyBool(key);};
_o.m$index=function(value){var x=$u;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};if($T(this.i$_contents[x].m$_eql2(value))){return(Hash.m$_x(x));};};return(nil);};
_o.m$inspect=function(){var contents=$u,x=$u;contents=[];for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};contents.m$push($Q('',Hash.m$_x(x).m$inspect(),' => ',this.i$_contents[x].m$inspect()));};return $Q('{',contents.m$join($q(', ')),'}');};
_o.m$invert=function(){var object=$u,x=$u;object=new(Red)();for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};object[this.i$_contents[x]]=x;};return new(Hash)(object);};
_o.m$keyBool=function(key){return this.m$hasKeyBool(key);};
_o.m$keys=function(){var keys=$u,x=$u;keys=[];for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};keys.m$push(Hash.m$_x(x));};return(keys);};
_o.m$length=function(){return this.m$size();};
_o.m$memberBool=function(key){return this.m$hasKeyBool(key);};
_o.m$merge=function(otherHash){return this.m$dup().m$update(otherHash);};
_o.m$mergeBang=function(otherHash){return this.m$update(otherHash);};
_o.m$reject=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');return this.m$dup().m$deleteIf(block);};
_o.m$rejectBang=function(block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var originalSize=$u;originalSize=this.m$size();return ($T(this.m$deleteIf(block).m$size().m$_eql2(originalSize))?nil:this);};
_o.m$replace=function(otherHash){return this.m$clear().m$update(otherHash);};
_o.m$select=function(_block){var blockGivenBool=(typeof(arguments[arguments.length-1])=='function');var array=$u,x=$u;array=[];for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};if($T(_block(Hash.m$_x(x),this.i$_contents[x]))){array.m$push([Hash.m$_x(x),this.i$_contents[x]]);};};return(array);};
_o.m$shift=function(){var result=$u,x=$u;result=typeof(this.i$_default)=='function'?this.i$_default():this.i$_default;for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};result=[Hash.m$_x(x),this.m$delete(Hash.m$_x(x))];break;};return(result);};
_o.m$size=function(){var size=$u,x=$u;size=0;for(var x in this.i$_contents){if($T(x.slice(1,2)=='_')){size=size.m$_plus(1);};};return(size);};
_o.m$sort=function(){return this.m$toA().m$sort();};
_o.m$store=function(key,value){return this.m$_breq(key,value);};
_o.m$toA=function(){var array=$u,x=$u;array=[];for(var x in this.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};array.m$push([Hash.m$_x(x),this.i$_contents[x]]);};return(array);};
_o.m$toHash=function(){return this;};
_o.m$toS=function(){return this.m$toA().m$join();};
_o.m$update=function(otherHash){var x=$u;for(x in otherHash.i$_contents){if(!$T(x.slice(1,2)=='_')){continue;};this.i$_contents[x]=otherHash.i$_contents[x];};return(this);};
_o.m$valueBool=function(value){return this.m$hasValueBool(value);};
_o.m$values=function(){var values=$u,x=$u;values=[];for(var x in this.i$_contents){if($T(x.slice(1,2)=='_')){continue;};values.m$push(this.i$_contents[x]);};return(values);};
_o.m$valuesAt=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);args=[];var i;for(i=0;i<_l;++i){args.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);var values=$u,i=$u;values=[];for(var i=0,l=args.length;i<l;++i){values.m$push(this.m$_brkt(args[i]));};return(values);};
_o.toString=function(){return this.m$inspect().toString()};
Hash.m$_x=function(x){var _switch=($q(x.slice(0,2)));if($q('s_').m$_eql3(_switch)){return($s(x.slice(2,x.length)));}else{if($q('q_').m$_eql3(_switch)){return($q(x.slice(2,x.length)));}else{if($q('i_').m$_eql3(_switch)){return(parseInt(x.slice(2,x.length)));}else{;};};};};});MatchData=function MatchData(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){MatchData[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){MatchData[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){MatchData.prototype[_x]=Red.prototype[_x];};};
MatchData.m$superclass=function superclass(){return Red;};
MatchData.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return MatchData;};
_o.m$initialize=function(){this.i$_captures=[];};
_o.m$_brkt=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);args=[];var i;for(i=0;i<_l;++i){args.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);return Array.prototype.m$slice.apply(this.i$_captures,args);};
_o.m$captures=function(){return this.i$_captures;};
_o.m$length=function(){return this.m$size();};
_o.m$size=function(){return this.i$_captures.length;};
_o.m$string=function(){return this.i$_string;};
_o.m$toA=function(){return this.m$captures();};
_o.m$toS=function(){return this.i$_captures[0];};
_o.m$inspect=function(){return $Q('#<MatchData:',this.m$objectId(),'>');};
_o.toString=function(){return this.m$inspect().toString()};});Regexp=function Regexp(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){Regexp[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Regexp[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Regexp.prototype[_x]=Red.prototype[_x];};};
Regexp.m$superclass=function superclass(){return Red;};
Regexp.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Regexp;};
var result=$u,captures=$u,i=$u;_o.m$initialize=function(regexp){this.i$_value=regexp.i$_value||regexp;};
_o.m$match=function(string){var result=$u,captures=$u,i=$u;result=new(MatchData)();if(!$T(captures=string.i$_value.match(this.i$_value))){return(nil);};for(var i=0,l=captures.length;i<l;++i){result.i$_captures[i]=$q(captures[i]);};result.i$_string=string;return(result);};
_o.m$inspect=function(){return(this.i$_value);};
_o.toString=function(){return this.m$inspect().toString()};});String=function String(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){String[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){String[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){String.prototype[_x]=Red.prototype[_x];};};
String.m$superclass=function superclass(){return Red;};
String.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return String;};
var result=$u,i=$u,originalValue=$u,separator=$u,pieces=$u;_o.m$initialize=function(string){this.i$_value=string.i$_value||string;};
_o.m$_perc=function(arg){return nil;};
_o.m$_star=function(integer){var result=$u,i=$u;result=$q('');for(var i=0,l=integer;i<l;++i){result.i$_value=result.i$_value.concat(this.i$_value);};return(result);};
_o.m$_plus=function(otherString){return new(String)(this.i$_value.concat(otherString.i$_value));};
_o.m$_ltlt=function(object){return this.m$concat(object);};
_o.m$_ltgt=function(otherString){return nil;};
_o.m$_eql2=function(object){return (_a=$T(object.m$isABool(String)))?((_c=$T(_b=this.i$_value===object.i$_value))?_b:_c):_a;};
_o.m$_eqti=function(object){return nil;};
_o.m$_brkt=function(object){return nil;};
_o.m$_breq=function(object){return nil;};
_o.m$capitalize=function(){return $q(this.i$_value.slice(0,1).toUpperCase()+this.i$_value.slice(1,this.i$_value.length).toLowerCase());};
_o.m$capitalizeBang=function(){var originalValue=$u;originalValue=this.i$_value;this.m$replace(this.m$capitalize());return(($T(originalValue===this.i$_value)?nil:this));};
_o.m$casecmp=function(otherString){return nil;};
_o.m$center=function(integer,padString){return nil;};
_o.m$chomp=function(separator){separator=$T(_a=separator)?_a:$q('\n');return nil;};
_o.m$chompBang=function(separator){separator=$T(_a=separator)?_a:$q('\n');return nil;};
_o.m$chop=function(){return nil;};
_o.m$chopBang=function(){return nil;};
_o.m$concat=function(object){this.i$_value=this.i$_value.concat(object.constructor==Number?NativeJS.String.fromCharCode(object):object.i$_value);return(this);};
_o.m$count=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);other_strings=[];var i;for(i=0;i<_l;++i){other_strings.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);return nil;};
_o.m$delete=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);other_strings=[];var i;for(i=0;i<_l;++i){other_strings.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);return nil;};
_o.m$deleteBang=function(){var blockGivenBool;var _l=(blockGivenBool?arguments.length-1:arguments.length);other_strings=[];var i;for(i=0;i<_l;++i){other_strings.push(arguments[i]);};var _block=(blockGivenBool?arguments[arguments.length-1]:nil);return nil;};
_o.m$downcase=function(){return $q(this.i$_value.toLowerCase());};
_o.m$downcaseBang=function(){var originalValue=$u;originalValue=this.i$_value;this.i$_value=this.i$_value.toLowerCase();return(originalValue===this.i$_value?nil:this);};
_o.m$each=function(separator){separator=$T(_a=separator)?_a:$q('\n');return nil;};
_o.m$eachByte=function(){return nil;};
_o.m$eachLine=function(separator){separator=$T(_a=separator)?_a:$q('\n');return nil;};
_o.m$emptyBool=function(){return this.i$_value.length==0;};
_o.m$eqlBool=function(){return nil;};
_o.m$gsub=function(pattern,replacement){return nil;};
_o.m$gsubBang=function(pattern,replacement){return nil;};
_o.m$hash=function(){return 'q_'+this;};
_o.m$hex=function(){var result=$u;result=parseInt(this.i$_value,16);return(($T(result.toString()=='NaN')?0:result));};
_o.m$includeBool=function(object){if(object.constructor==Number){object=$q(NativeJS.String.fromCharCode(object));};return new RegExp(object.i$_value).test(this.i$_value);};
_o.m$index=function(){return nil;};
_o.m$inspect=function(){return $Q('"',this,'"');};
_o.m$match=function(pattern){return $r(pattern).m$match(this);};
_o.m$oct=function(){var result=$u;result=parseInt(this.i$_value,8);return(($T(result.toString()=='NaN')?0:result));};
_o.m$replace=function(otherString){this.i$_value=otherString.i$_value;return(this);};
_o.m$split=function(pattern){var result=$u,pieces=$u,i=$u;result=[];pieces=this.i$_value.split(new RegExp(pattern.i$_value));for(var i=0,l=pieces.length;i<l;++i){result.push($q(pieces[i]));};return(result);};
_o.m$toS=function(){return(this);};
_o.m$toStr=function(){return(this);};
_o.m$toSym=function(){return $s(this.i$_value);};
_o.m$upcase=function(){return $q(this.i$_value.toUpperCase());};
_o.m$upcaseBang=function(){var originalValue=$u;originalValue=this.i$_value;this.i$_value=this.i$_value.toUpperCase();return(originalValue===this.i$_value?nil:this);};
_o.toString=function(){return this.i$_value;};});Symbol=function Symbol(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){Symbol[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Symbol[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Symbol.prototype[_x]=Red.prototype[_x];};};
Symbol.m$superclass=function superclass(){return Red;};
Symbol.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Symbol;};
var result=$u,x=$u;Symbol.c$_table=new(Object)();
Symbol.m$allSymbols=function(){var result=$u,x=$u;result=[];for(var x in Symbol.c$_table){if($T(Symbol.c$_table[x].constructor==Symbol)){result.m$push(Symbol.c$_table[x]);};};return(result);};
_o.m$initialize=function(value){this.i$_value=value;Symbol.c$_table[value]=this;};
_o.m$hash=function(){return 's_'+this.i$_value;};
_o.m$id2name=function(){return $q(this.i$_value);};
_o.m$inspect=function(){return $Q(':',this.i$_value);};
_o.m$toI=function(){return this.m$objectId();};
_o.m$toInt=function(){return this.m$objectId();};
_o.m$toS=function(){return this.m$id2name();};
_o.m$toSym=function(){return(this);};
delete Symbol.prototype.m$dup;
delete Symbol.prototype.m$clone;
_o.toString=function(){return this.m$inspect().toString()};});Time=function Time(){this.m$_assignId();this.m$initialize.apply(this,arguments)};
var _x;for(_x in Class.prototype){Time[_x]=Class.prototype[_x];};
var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Time[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Time.prototype[_x]=Red.prototype[_x];};};
Time.m$superclass=function superclass(){return Red;};
Time.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Time;};
var result=$u;Time.m$at=function(seconds){var result=$u;result=new(Time)();result.i$_value=new(Date)(seconds*1000);return(result);};
Time.m$now=function(){return new(Time)();};
_o.m$initialize=function(){this.i$_value=new(Date);};
_o.m$_plus=function(numeric){return Time.m$at(this.m$toI()+numeric);};
_o.m$day=function(){return this.i$_value.getDate();};
_o.m$hash=function(){return 't_'+this.m$toF();};
_o.m$mday=function(){return this.m$day();};
_o.m$succ=function(){return Time.m$at(this.m$toI()+1);};
_o.m$toF=function(){return this.i$_value.valueOf()/1000;};
_o.m$toI=function(){return Math.floor(this.i$_value.valueOf()/1000);};
_o.m$toS=function(){return $q(this.i$_value.toString());};
_o.m$tvSec=function(){return this.m$toI();};
_o.m$tvUsec=function(){return this.m$usec();};
_o.m$usec=function(){return (this.i$_value.valueOf()*1000)-(Math.floor(this.i$_value.valueOf()/1000)*1000000);};
_o.m$wday=function(){return this.i$_value.getDay();};
_o.m$year=function(){return this.i$_value.getFullYear();};
_o.toString=function(){return this.i$_value.toString()};});var _x;for(_x in Red){if(_x.slice(0,2)==='c$'){Number[_x]=Red[_x];};};
var _x;for(_x in Red.prototype){if(_x.slice(0,2)==='m$'){Number.prototype[_x]=Red.prototype[_x];};};
Number.m$superclass=function superclass(){return Red;};
Number.m$instanceEval(function(){var _o=this.prototype;
_o.m$class=function class(){return Number;};
var raise=$u;_o.m$_star=function(object){return this*object;};
_o.m$_slsh=function(object){return this/object;};
_o.m$_plus=function(otherNumber){return this+otherNumber;};
_o.m$_subt=function(otherNumber){return this-otherNumber;};
_o.m$_ltgt=function(object){var raise=$u;if(!$T(object.m$isABool(Number))){raise;};if($T(this<object)){return(-1);};if($T(this>object)){return(1);};if($T(this==object)){return(0);};};
_o.m$_lthn=function(object){return this.m$_ltgt(object) == -1;};
_o.m$_lteq=function(object){return [-1,0].m$includeBool(this.m$_ltgt(object));};
_o.m$_eql2=function(object){if(!$T(object.m$isABool(Number))){return(false);};return this.m$_ltgt(object) == 0;};
_o.m$_gteq=function(object){return [0,1].m$includeBool(this.m$_ltgt(object));};
_o.m$_gthn=function(object){return this.m$_ltgt(object) == 1;};
_o.m$hash=function(){return 'i_'+this;};
_o.m$toS=function(){return $q(this.toString());};});function $q(string){if(typeof string!=='string'){return string;};return new String(string);};function $r(string){return new(Regexp)(string);};function $s(string){return(Symbol.c$_table[string]||new(Symbol)(string));};function $Q(){var s=$q(arguments[0]);for(var i=1,l=arguments.length;i<l;i++){s=s.m$_plus($q(arguments[i].m$toS?arguments[i].m$toS():arguments[i].toString()));};return s;};function $S(){var s=$q(arguments[0]);for(var i=1,l=arguments.length;i<l;i++){s=s.m$_plus($q(arguments[i].m$toS?arguments[i].m$toS():arguments[i].toString()));};return $s(s.toString());};function $T(x){return x!==false&&x!==nil&&x!=undefined;};m$puts=function puts(string){console.log($q(string).m$toS().toString());return nil;}